### ISSUE TITLE
Unable to locate libwebp during build process (winbuild)

### ISSUE THREAD

**Issue by Buchi013** [openslide/openslide-bin#243]
**Environment:** Ubuntu 22.04 WSL

I am trying to build Windows binaries of Openslide to read Tiff files compressed with WebP. `libwebp` and its `.pc` files are present on my system (`/usr/local/`), but are not found during the build process inside the provided winbuild docker image:

![grafik](https://github.com/openslide/openslide-bin/assets/74509594/0da6dd42-fe51-4918-b88c-9ca8f250ab2b)

When building directly from source on the same system, without `openslide-bin` i get functioning (linux) binaries, able to handle WebP-TIFFs.

I suspected this might be due pkg-config searching different directories inside and outside the docker image:

Ubuntu: `/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig`

Docker: `/usr/lib64/pkgconfig:/usr/share/pkgconfig`

However placing libwebp.pc in one of the two directories inside docker did not solve the issue.

### Questions:
1. How can I configure the winbuild tool within the Docker image to correctly locate libwebp during the build process?
2. Is there a way to build the windows binaries (with libtiff including libwebp) directly from source on a Linux/WSL system?

Thanks in advance!

**Comment by bgilbert** [comment]
Builds performed by openslide-bin are completely self-contained: openslide-bin must know about all dependencies and must build them itself.  You'll need to teach openslide-bin to build libwebp.  Once you do this, you can build Windows binaries from either Linux or WSL as you'd like.

All of the dependencies must be built with Meson, including those that don't natively include Meson support.  Fortunately, Meson's [wrapdb](https://github.com/mesonbuild/wrapdb) already has a Meson port of libwebp.

The needed changes are:

1. Add wrapdb's wrap file to [`subprojects`](https://github.com/openslide/openslide-bin/tree/main/subprojects) by running `meson wrap install libwebp`.
2. Add libwebp to [`_PROJECTS` in `software.py`](https://github.com/openslide/openslide-bin/blob/9801304d2b8d3e4b8dc63558db94216dd16baca6/common/software.py#L196).  You can test the `update_url`/`update_regex` by running `./bintool updates`.
3.  Modify [`deps/meson.build`](https://github.com/openslide/openslide-bin/blob/main/deps/meson.build) to invoke the build, in the correct order relative to the other dependencies.  Pass any necessary [options](https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/libwebp/meson_options.txt) as parameters, e.g. disabling building of command-line tools to reduce build time.

Note that newly-added dependencies sometimes have build bugs that need to be fixed in wrapdb or upstream, then [patched](https://github.com/openslide/openslide-bin/tree/main/subprojects/packagefiles) in openslide-bin with a `diff_files` directive.  Common problems include libraries a) not correctly filtering their exported symbols or b) taking a dependency on winpthreads when they don't actually use it.  Either case will cause the build or smoke test to fail.

**Comment by bgilbert** [comment]
Out of curiosity, do you have a slide scanner that produces WebP TIFFs?

**Comment by Buchi013** [comment]
Thank you very much for your help! 

I followed your instructions (the library did indeed take a dependency on pthreads, which was fixable with a patch file as you described), and was able to create working Windows binaries capable of opening WebP-TIFFs.

I do not have a scanner that produces those files, but am currently experimenting with WebP-TIFFs (mainly converted from Aperio .svs/.tif files) for my bachelor thesis.

**Comment by bgilbert** [comment]
Cool, glad you got it working!
